modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Povstalec/StargateJourney/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="sgjourney_large.png"
credits="${mod_credits}"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies."${mod_id}"]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="computercraft"
    type="optional"
    versionRange="${cct_version_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="jei"
    type="optional"
    versionRange="${jei_version_range}"
    ordering="AFTER"
    side="BOTH"
[[dependencies."${mod_id}"]]
    modId="stellarview"
    type="optional"
    versionRange="${sv_version_range}"
    ordering="AFTER"
    side="CLIENT"

